export const servicesTypes = {
  // Sync
  FETCH_SERVICES_REQUEST: 'services/FETCH_SERVICES_REQUEST',
  FETCH_SERVICES_SUCCESS: 'services/FETCH_SERVICES_SUCCESS',
  FETCH_SERVICES_FAILURE: 'services/FETCH_SERVICES_FAILURE',

  // Async
  FETCH_SERVICES_ASYNC: 'services/FETCH_SERVICES_ASYNC',

  // Sync
  FETCH_CURRENT_SERVICE_REQUEST: 'services/FETCH_CURRENT_SERVICE_REQUEST',
  FETCH_CURRENT_SERVICE_SUCCESS: 'services/FETCH_CURRENT_SERVICE_SUCCESS',
  FETCH_CURRENT_SERVICE_FAILURE: 'services/FETCH_CURRENT_SERVICE_FAILURE',

  // Async
  FETCH_CURRENT_SERVICE_ASYNC: 'services/FETCH_CURRENT_SERVICE_ASYNC',
};
